###
POST http://localhost:9000/api/createsucur HTTP/1.1
Content-Type: application/json

 {
     "codsucur": "xdddd",
     "descripsucur": "1",
     "almacensucur":"00005",
     "codciusucur":{"codciud": 1, "dptciusucur": 1, "ciuciusucur": 1},
     "telsucur": 3186877835,
     "direccsucur": "Calle 29 #3-56",
     "activosucur": "S",
     "anomessucur": 1
 }

###
GET http://localhost:9000/api/getdata HTTP/1.1

###
GET http://localhost:9000/api/getdata/621d38c7d672a29dbe0de23e HTTP/1.1

###
PUT http://localhost:9000/api/putdata/621d38c7d672a29dbe0de23e HTTP/1.1
Content-Type: application/json

 {
     "codsucur": "xd",
     "descripsucur": "edit",
     "almacensucur":"00005",
     "codciusucur":{"codciud": 1, "dptciusucur": 1, "ciuciusucur": 1},
     "telsucur": 3186877835,
     "direccsucur": "Calle 29 #3-56",
     "activosucur": "S",
     "anomessucur": 10000
 }

###
DELETE  http://localhost:9000/api/deletedata/6218f755479cf2554d977143 HTTP/1.1